server:
  port: 3000

spring:
  application:
    name: example-microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: example_microservice
    password: example_microservice
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true